//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gse.WebService.Demo.EmpresaServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="EmpresaServiceReference.IEmpresaService")]
    public interface IEmpresaService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/GetAllEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/GetAllEmpresaResponse")]
        Gse.WebService.Entities.EmpresaData[] GetAllEmpresa();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/GetAllEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/GetAllEmpresaResponse")]
        System.Threading.Tasks.Task<Gse.WebService.Entities.EmpresaData[]> GetAllEmpresaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/GetEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/GetEmpresaResponse")]
        Gse.WebService.Entities.EmpresaData GetEmpresa(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/GetEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/GetEmpresaResponse")]
        System.Threading.Tasks.Task<Gse.WebService.Entities.EmpresaData> GetEmpresaAsync(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/AddEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/AddEmpresaResponse")]
        void AddEmpresa(Gse.WebService.Entities.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/AddEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/AddEmpresaResponse")]
        System.Threading.Tasks.Task AddEmpresaAsync(Gse.WebService.Entities.EmpresaData empresa);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/DeleteEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/DeleteEmpresaResponse")]
        void DeleteEmpresa(System.Guid Id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IEmpresaService/DeleteEmpresa", ReplyAction="http://tempuri.org/IEmpresaService/DeleteEmpresaResponse")]
        System.Threading.Tasks.Task DeleteEmpresaAsync(System.Guid Id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IEmpresaServiceChannel : Gse.WebService.Demo.EmpresaServiceReference.IEmpresaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresaServiceClient : System.ServiceModel.ClientBase<Gse.WebService.Demo.EmpresaServiceReference.IEmpresaService>, Gse.WebService.Demo.EmpresaServiceReference.IEmpresaService {
        
        public EmpresaServiceClient() {
        }
        
        public EmpresaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Gse.WebService.Entities.EmpresaData[] GetAllEmpresa() {
            return base.Channel.GetAllEmpresa();
        }
        
        public System.Threading.Tasks.Task<Gse.WebService.Entities.EmpresaData[]> GetAllEmpresaAsync() {
            return base.Channel.GetAllEmpresaAsync();
        }
        
        public Gse.WebService.Entities.EmpresaData GetEmpresa(System.Guid Id) {
            return base.Channel.GetEmpresa(Id);
        }
        
        public System.Threading.Tasks.Task<Gse.WebService.Entities.EmpresaData> GetEmpresaAsync(System.Guid Id) {
            return base.Channel.GetEmpresaAsync(Id);
        }
        
        public void AddEmpresa(Gse.WebService.Entities.EmpresaData empresa) {
            base.Channel.AddEmpresa(empresa);
        }
        
        public System.Threading.Tasks.Task AddEmpresaAsync(Gse.WebService.Entities.EmpresaData empresa) {
            return base.Channel.AddEmpresaAsync(empresa);
        }
        
        public void DeleteEmpresa(System.Guid Id) {
            base.Channel.DeleteEmpresa(Id);
        }
        
        public System.Threading.Tasks.Task DeleteEmpresaAsync(System.Guid Id) {
            return base.Channel.DeleteEmpresaAsync(Id);
        }
    }
}
